name: Deploy Go Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-cicds-myapp:$(date +%s)

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Go application
      run: go build -o go-cicds

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: . 
        file: Dockerfile 

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: bu
    - name: Push Docker image
      run: docker push siwakorn2345/go-cicds-myapp:${{ github.sha }} 
