name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: go build -o main

      - name: Test
        run: go test ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy to GitHub Pages
        uses: SiwakornEDZ/go-k8s-cicds@4.1.1
        with:
          branch: cicd
          folder: .
          clean: true 
          token: ${{ secrets.GITHUB_TOKEN }}
