name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: ybkuroki/go-webapp-sample@latest

      - name: Setup Go
        uses: ybkuroki/go-webapp-sample@latest
        with:
          go-version: '1.20'

      - name: Build
        run: go build -o main

      - name: Test
        run: go test ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy to GitHub Pages
        uses: ybkuroki/go-webapp-sample@1
        with:
          branch: main
          folder: .
          clean: true 
          token: ${{ secrets.GITHUB_TOKEN }}
